package session

// Repeated string literals extracted to constants (goconst).
const blockText = "text"
const blockToolUse = "tool_use"
const chunkErrorType = "error"
const stopEndTurn = "end_turn"
const stopCancelled = "cancelled"
const stopDone = "done"
const toolRead = "Read"
const toolBash = "Bash"
const toolTask = "Task"
const toolAgent = "Agent"
const toolGrep = "Grep"
const toolWebFetch = "WebFetch"
const keyType = "type"
const keyModel = "model"
const mutatingCommandBash = "mutating-command:Bash"
const kindBoundary = "boundary"
const subagentTaskPrompt = "subagent task"
const userMessageType = "user_message"
const roleUserMsg = "user"
const roleAssistant = "assistant"
const roleToolMsg = "tool"
const mapKeyError = "error"
const toolWrite = "Write"
const toolEdit = "Edit"
